[build]
command = npm run build:ssr"
commandOrigin = "config"
publish = "dist/logistics/browser/"
publishOrigin = " config"
functionsDirectory =  "/opt/build/repo/netlify/functions"

[[plugins]]
inputs = {}
origin = "config"
package = '@netlify/angular-runtime'
