[build]
command = "ng build"
commandOrigin = "config"
publish = "dist/logistics/browser/browser"
publishOrigin = " config"
functionsDirectory =  "/opt/build/repo/netlify/functions"

[[plugins]]
inputs = {}
origin = "config"
package = '@netlify/angular-runtime'
